import { Film, Library, MessageCircle, Rss } from 'lucide-react';

export type Product = {
  photo_url: string;
  name: string;
  description: string;
  created_at: string;
  price: number;
  id: number;
  category: string;
  updated_at: string;
};

export interface SaleUser {
  id: number;
  name: string;
  email: string;
  amount: string;
  image: string;
  initials: string;
}

export const recentSalesData: SaleUser[] = [
  {
    id: 1,
    name: 'Olivia Martin',
    email: 'olivia.martin@email.com',
    amount: '+$1,999.00',
    image: 'https://api.slingacademy.com/public/sample-users/1.png',
    initials: 'OM'
  },
  {
    id: 2,
    name: 'Jackson Lee',
    email: 'jackson.lee@email.com',
    amount: '+$39.00',
    image: 'https://api.slingacademy.com/public/sample-users/2.png',
    initials: 'JL'
  },
  {
    id: 3,
    name: 'Isabella Nguyen',
    email: 'isabella.nguyen@email.com',
    amount: '+$299.00',
    image: 'https://api.slingacademy.com/public/sample-users/3.png',
    initials: 'IN'
  },
  {
    id: 4,
    name: 'William Kim',
    email: 'will@email.com',
    amount: '+$99.00',
    image: 'https://api.slingacademy.com/public/sample-users/4.png',
    initials: 'WK'
  },
  {
    id: 5,
    name: 'Sofia Davis',
    email: 'sofia.davis@email.com',
    amount: '+$39.00',
    image: 'https://api.slingacademy.com/public/sample-users/5.png',
    initials: 'SD'
  }
];

export const JAVBUS = 'https://www.javbus.com';

/* 爬取页面超时时间 */
export const JAVBUS_TIMEOUT = 5000;

export const USER_AGENT =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36';

export const RANKINGS_CACHE_DURATION_MS = 60 * 60 * 1000 * 6; // 6 小时
export const RANKINGS_JAVDB_BASE_URL = 'https://javdb.com/rankings/movies';

export const ARANKINGS_CCESS_DENIED_MESSAGE =
  '由於版權限制，本站禁止了你的網路所在國家的訪問。';
export const DOCKER_MOUNT_PATH = './media'; // 容器内挂载的媒体目录
export const SubscribeMovieStatusMap = {
  subscribed: {
    label: '已订阅',
    variant: 'destructive'
  },
  downloading: {
    label: '下载中',
    variant: 'destructive'
  },
  downloaded: {
    label: '已下载',
    variant: 'destructive'
  },
  added: {
    label: '已入库',
    variant: 'destructive'
  }
};

export const BASE_PARSE_CONFIG: MovieParseConfig = {
  nfoTitleRule: "number title",
  directoryRule: "year/letters/[number]-actor",
  downloadFanart: true,
  fileNamingRule: "number",
  watermarkTypes: ["subtitles", "cracked", "leaked", "uncensored"],
  cleanupExtensions: ".html|.url",
  cleanupMinFileSize: 10,
  enableAiTranslation: false,
  cleanupFilenameContains: "直 播 盒 子|最 新 情 報|最 新 位 址|注册免费送|房间火爆|美女荷官|妹妹直播|精彩直播"
}

export const videoExtensions = [
  '.mp4',
  '.mkv',
  '.avi',
  '.mov',
  '.wmv',
  '.flv',
  '.webm',
  '.mpeg',
  '.mpg'
];

export const imageExtensions = [
  '.jpg',
  '.jpeg',
  '.png',
  '.gif',
  '.webp',
  '.bmp',
  '.svg',
  '.ico'
];

export const ALLOWED_DOMAINS = [
  'www.javbus.com',
  'javbus.com',
  'pics.dmm.co.jp',
  'dmm.co.jp',
  'awsimgsrc.dmm.co.jp',
  'image.mgstage.com'
  // 在这里添加其他你需要的图片来源域名
];

export const FORUMS = ['2048', 'sehuatang', 'javbus', 't66y', 'southPlus'];

export const FORUM_MAP = {
  f2048: 'https://hjd2048.com',
  sehuatang: 'https://www.sehuatang.net',
  javbus: 'https://www.javbus.com',
  t66y: 'https://t66y.com/thread0806.php',
  southPlus: 'https://www.south-plus.net'
};
export const BASE_HEADER = {
  accept:
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'user-agent':
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36'
};

export const SCHEDULED_TASKS = [
  {
    id: 'javbus-movie-update',
    name: 'JAV 影片更新',
    initial: '更',
    schedule: '30 */6 * * *',
    status: '运行中',
    description: '为已订阅的影片获取磁力链接并发送下载请求。',
    icon: Film
  },
  {
    id: 'javbus-subscribe-update',
    name: 'JAV 订阅更新',
    initial: '订',
    schedule: '0 */12 * * *',
    status: '运行中',
    description: '扫描所有 JAVBus 订阅源，查找并保存新的影片。',
    icon: Rss
  },

  // {
  //   id: 'download-status-sync',
  //   name: '下载状态同步',
  //   initial: '下',
  //   schedule: '*/5 * * * *',
  //   status: '运行中',
  //   description: '与下载器客户端同步，更新数据库中所有任务的下载状态。',
  //   icon: Download,
  // },
  {
    id: 'media-scraping',
    name: '媒体刮削',
    initial: '刮',
    schedule: '*/10 * * * *',
    description: '刮削媒体库中的影片。',
    status: '运行中',
    icon: Rss
  },

  {
    id: 'media-library-sync',
    name: '媒体库同步',
    initial: '同',
    schedule: '*/10 * * * *',
    description: '同步媒体库中的影片到数据库。',
    status: '运行中',
    icon: Library
  },
  {
    id: 'forum-update',
    name: '论坛更新',
    initial: '论',
    schedule: '*/10 * * * *',
    description: '扫描所有论坛订阅源，查找并保存新的帖子。',
    status: '运行中',
    icon: MessageCircle
  }
];


export const genres = [
  { "name": "主题", "genres": ["折磨", "嘔吐", "觸手", "蠻橫嬌羞", "處男", "正太控", "出軌", "瘙癢", "運動", "女同接吻", "性感的", "美容院", "處女", "爛醉如泥的", "殘忍畫面", "妄想", "惡作劇", "學校作品", "粗暴", "通姦", "姐妹", "雙性人", "跳舞", "性奴", "倒追", "性騷擾", "其他", "戀腿癖", "偷窥", "花癡", "男同性恋", "情侶", "戀乳癖", "亂倫", "其他戀物癖", "偶像藝人", "野外・露出", "獵豔", "女同性戀", "企畫", "10枚組", "科幻", "女優ベスト・総集編", "温泉", "M男", "原作コラボ", "16時間以上作品", "デカチン・巨根", "ファン感謝・訪問", "動画", "巨尻", "ハーレム", "日焼け", "早漏", "キス・接吻", "汗だく", "スマホ専用縦動画", "Vシネマ", "Don Cipote's choice", "アニメ", "アクション", "イメージビデオ（男性）", "孕ませ", "ボーイズラブ", "ビッチ", "特典あり（AVベースボール）", "コミック雑誌", "時間停止"] },
  {
    "name": "角色", "genres": ["黑幫成員",
      "童年朋友",
      "公主",
      "亞洲女演員",
      "伴侶",
      "講師",
      "婆婆",
      "格鬥家",
      "女檢察官",
      "明星臉",
      "女主人、女老板",
      "模特兒",
      "秘書",
      "美少女",
      "新娘、年輕妻子",
      "姐姐",
      "格鬥家",
      "車掌小姐",
      "寡婦",
      "千金小姐",
      "白人",
      "已婚婦女",
      "女醫生",
      "各種職業",
      "妓女",
      "賽車女郎",
      "女大學生",
      "展場女孩",
      "女教師",
      "母親",
      "家教",
      "护士",
      "蕩婦",
      "黑人演員",
      "女生",
      "女主播",
      "高中女生",
      "服務生",
      "魔法少女",
      "學生（其他）",
      "動畫人物",
      "遊戲的真人版",
      "超級女英雄",]
  },
  {
    "name": "服裝", "genres": ["女戰士",
      "及膝襪",
      "娃娃",
      "女忍者",
      "女裝人妖",
      "內衣",
      "猥褻穿著",
      "兔女郎",
      "貓耳女",
      "女祭司",
      "泡泡襪",
      "制服",
      "緊身衣",
      "裸體圍裙",
      "迷你裙警察",
      "空中小姐",
      "連褲襪",
      "身體意識",
      "OL",
      "和服・喪服",
      "體育服",
      "內衣",
      "水手服",
      "學校泳裝",
      "旗袍",
      "女傭",
      "迷你裙",
      "校服",
      "泳裝",
      "眼鏡",
      "角色扮演",
      "哥德蘿莉",]
  },
  {
    "name": "體型", "genres": ["超乳",
      "肌肉",
      "乳房",
      "嬌小的",
      "屁股",
      "高",
      "變性者",
      "無毛",
      "胖女人",
      "苗條",
      "孕婦",
      "成熟的女人",
      "蘿莉塔",
      "貧乳・微乳",
      "巨乳",]
  },
  {
    "name": "行為", "genres": ["顏面騎乘",
      "食糞",
      "足交",
      "母乳",
      "手指插入",
      "按摩",
      "女上位",
      "舔陰",
      "拳交",
      "深喉",
      "69",
      "淫語",
      "潮吹",
      "乳交",
      "排便",
      "飲尿",
      "口交",
      "濫交",
      "放尿",
      "打手槍",
      "吞精",
      "肛交",
      "顏射",
      "自慰",
      "顏射",
      "中出",
      "肛内中出",]
  },
  {
    "name": "玩法", "genres": ["立即口交",
      "女優按摩棒",
      "子宮頸",
      "催眠",
      "乳液",
      "羞恥",
      "凌辱",
      "拘束",
      "輪姦",
      "插入異物",
      "鴨嘴",
      "灌腸",
      "監禁",
      "紧缚",
      "強姦",
      "藥物",
      "汽車性愛",
      "SM",
      "糞便",
      "玩具",
      "跳蛋",
      "緊縛",
      "按摩棒",
      "多P",
      "性愛",
      "假陽具",
      "逆強姦",]
  },
  {
    "name": "類別", "genres": ["合作作品",
      "恐怖",
      "給女性觀眾",
      "教學",
      "DMM專屬",
      "R-15",
      "R-18",
      "3D",
      "特效",
      "故事集",
      "限時降價",
      "複刻版",
      "戲劇",
      "戀愛",
      "高畫質",
      "主觀視角",
      "介紹影片",
      "4小時以上作品",
      "薄馬賽克",
      "經典",
      "首次亮相",
      "數位馬賽克",
      "投稿",
      "纪录片",
      "國外進口",
      "第一人稱攝影",
      "業餘",
      "局部特寫",
      "獨立製作",
      "DMM獨家",
      "單體作品",
      "合集",
      "高清",
      "字幕",
      "天堂TV",
      "DVD多士爐",
      "AV OPEN 2014 スーパーヘビー",
      "AV OPEN 2014 ヘビー級",
      "AV OPEN 2014 ミドル級",
      "AV OPEN 2015 マニア/フェチ部門",
      "AV OPEN 2015 熟女部門",
      "AV OPEN 2015 企画部門",
      "AV OPEN 2015 乙女部門",
      "AV OPEN 2015 素人部門",
      "AV OPEN 2015 SM/ハード部門",
      "AV OPEN 2015 女優部門",
      "AVOPEN2016人妻・熟女部門",
      "AVOPEN2016企画部門",
      "AVOPEN2016ハード部門",
      "AVOPEN2016マニア・フェチ部門",
      "AVOPEN2016乙女部門",
      "AVOPEN2016女優部門",
      "AVOPEN2016ドラマ・ドキュメンタリー部門",
      "AVOPEN2016素人部門",
      "AVOPEN2016バラエティ部門",
      "VR専用",
      "堵嘴·喜劇",
      "幻想",
      "性別轉型·女性化",
      "為智能手機推薦垂直視頻",
      "設置項目",
      "迷你係列",
      "體驗懺悔",
      "黑暗系統",]
  },
  {
    "name": "其他", "genres": ["オナサポ",
      "アスリート",
      "覆面・マスク",
      "ハイクオリティVR",
      "ヘルス・ソープ",
      "ホテル",
      "アクメ・オーガズム",
      "花嫁",
      "デート",
      "軟体",
      "娘・養女",
      "スパンキング",
      "スワッピング・夫婦交換",
      "部下・同僚",
      "旅行",
      "胸チラ",
      "バック",
      "エロス",
      "男の潮吹き",
      "女上司",
      "セクシー",
      "受付嬢",
      "ノーブラ",
      "白目・失神",
      "M女",
      "女王様",
      "ノーパン",
      "セレブ",
      "病院・クリニック",
      "面接",
      "お風呂",
      "叔母さん",
      "罵倒",
      "お爺ちゃん",
      "逆レイプ",
      "ディルド",
      "ヨガ",
      "飲み会・合コン",
      "部活・マネージャー",
      "お婆ちゃん",
      "ビジネススーツ",
      "チアガール",
      "ママ友",
      "エマニエル",
      "妄想族",
      "蝋燭",
      "鼻フック",
      "放置",
      "サンプル動画",
      "サイコ・スリラー",
      "ラブコメ",
      "オタク",
      "4K",
      "福袋",
      "玩具責め",
      "女優",
      "お掃除フェラ",
      "筆おろし",
      "美脚",
      "美尻",
      "フェチ",
      "羞恥プレイ",
      "逆ナンパ",
      "着衣",
      "誘惑",
      "チラリズム",
      "写真集",
      "書籍版",
      "SM拘束",
      "ドキュメント",
      "グッズ",
      "Tシャツ",
      "失禁",
      "オナホール",
      "カップホール",
      "非貫通",
      "ローション付き",
      "配信専用",
      "官能小説",
      "CD",
      "生挿入",
      "風俗",
      "外国人",
      "淫語責め",
      "アナルファック",
      "脚コキ",
      "オイルプレイ",
      "キャバ嬢",
      "調教",
      "ローション・オイル",
      "媚薬",
      "顔面騎乗位",
      "微乳",
      "デカチン",
      "3P、4P",
      "野外",
      "露出",
      "レイプ",
      "ベスト、総集編",
      "マジックミラー号",
      "看護師",
      "アイドル",
      "妹",
      "スクール水着",
      "デリヘル",
      "凌辱",
      "童貞モノ",
      "ブルマ",
      "ホテヘル",
      "縛り",
      "ロリータ",
      "ミニスカート",
      "尻",
      "奴隷",
      "芸能人",
      "下着",
      "母親",
      "湯",
      "教師",
      "ストッキング",
      "電車、バス",
      "健康診断",
      "野球拳",
      "浴衣",
      "爆乳",
      "ソープ",
      "スワッピング",
      "メガネ",
      "素股",
      "ドリンク",
      "フルハイビジョン(FHD)",
      "三十路",
      "羞恥・辱め",
      "パンチラモノ",
      "放尿・失禁",
      "五十路",
      "ショートヘアー",
      "着物・浴衣",
      "清楚",
      "四十路",
      "VR",
      "オモチャ",
      "エステ・マッサージ",
      "Gカップ",
      "目隠し",
      "ドラッグ・媚薬",
      "六十路",
      "淫語モノ",
      "口内発射",
      "童顔",
      "スチュワーデス・CA",
      "Dカップ",
      "美熟女",
      "MGSだけのおまけ映像付き",
      "手マン",
      "パンストモノ",
      "フェラモノ",
      "性教育",
      "HowTo",
      "MGS限定特典映像",
      "寝取り･寝取られ",
      "Eカップ",
      "Fカップ",
      "ロングヘアー",
      "黒髪",
      "ショートヘア",
      "金髪",
      "茶髪",
      "女子高生",
      "ハーフ",
      "金髪・ブロンド",
      "初撮り",
      "介護",
      "Hカップ",
      "期間限定販売",
      "多人数",
      "風俗嬢",
      "PICKUP素人",
      "オイル・ローション",
      "8KVR",
      "プレステージ20周年特別企画",
      "口内射精",
      "美女",
      "MGSだけの特典映像付",
      "色白",
      "総集編・ベスト",
      "近●相●",
      "ハイビジョン(HD)",
      "配信専用素人",
      "台湾モデル",
      "ショートカット",
      "巨乳",
      "清楚",
      "お姉さん",
      "長身",
      "ギャル",
      "美乳",
      "パイパン",
      "スレンダー",
      "貧乳・微乳",
      "ミニ系",
      "小柄",
      "くびれ",
      "ぽっちゃり",
      "黒髪",
      "色白",
      "金髪",
      "茶髪",
      "美脚",
      "ロングヘアー",
      "外国人",
      "ショートヘアー",
      "お嬢様・令嬢",
      "ミディアムヘアー",
      "AI生成作品",
      "個人撮影",
      "アナルセックス（男の娘）"]
  },
]
