import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconFolder,
  IconUsers,
  IconCrown,
  IconStar,
  IconBox,
  IconAdjustmentsDown,
  IconSearch,
  IconListCheck,
  IconRss,
  IconBrandTelegram,
  IconChartBarPopular,
  IconMovie,
  IconMessage,
  IconLayersSelected,
  IconFileRss,
  IconAdjustmentsSearch
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  downloader: IconAdjustmentsDown,
  search: IconSearch,
  listCheck: IconListCheck,
  rss: IconRss,
  telegram: IconBrandTelegram,
  recommended: IconChartBarPopular,
  movie: IconMovie,
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  forum: IconMessage,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  layersSelected: IconLayersSelected,
  sun: IconSun,
  moon: IconMoon,
  fileRss: IconFileRss,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  adjustSearch: IconAdjustmentsSearch
};
